cds-snc/url-shortener

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml
Initial setup of a VS Code .devcontainer setup
Create the devcontainer.json, docker-compose.yml and Dockerfile
=> Initial setup of devcontainer development environment

.github/workflows/export_github_data.yml
Adds the GitHub metadata exporter for Sentinel
=> Create  export_github_data.yml

adr/attachments/temp.md, adr/template.md
Adding ADR directory and template (borrowed from Notify) #30 
---
None
---
=> Chore add adr

api/requirements.txt
Updating cryptography and starlett package to versions compatible in the application as renovate updated those packages thus causing inconsistencies and conflicts.
Had to recreate PR since all commits had to be signed.
=> Update cryptography and starlette packages

.github/workflows/tf_apply_production.yml, .github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_production.yml, .github/workflows/tf_plan_staging.yml, .gitignore, terragrunt/aws/hosted_zone/outputs.tf, terragrunt/aws/hosted_zone/route53.tf, terragrunt/env/production/hosted_zone/terragrunt.hcl, terragrunt/env/staging/hosted_zone/terragrunt.hcl
Terraform/terragrunt files needed to created the hosted zone in the staging and production environments.
=> Hosted zone infrastructure

.github/workflows/tf_apply_production.yml, .github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_production.yml, .github/workflows/tf_plan_staging.yml, terragrunt/aws/ecr/ecr.tf, terragrunt/aws/ecr/outputs.tf, terragrunt/env/production/ecr/terragrunt.hcl, terragrunt/env/staging/ecr/terragrunt.hcl
Terraform code for creating an ECR instance associated with the URL shortener in staging and production. In addition, the github action files were modified to include the ECR. 
Closes #71
=> Terraform code for ECR

api/main.py
Closes #32 by adding a `"/.well-known/security.txt"` route.
=> feat: security.txt

.github/workflows/tf_apply_production.yml, .github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_production.yml, .github/workflows/tf_plan_staging.yml, .gitignore, terragrunt/aws/network/outputs.tf, terragrunt/aws/network/security-groups.tf, terragrunt/aws/network/security_groups.tf, terragrunt/aws/network/vpc.tf, terragrunt/env/production/network/terragrunt.hcl, terragrunt/env/staging/network/terragrunt.hcl
Closes #67. PR to create the VPC, its associated endpoints and security groups in AWS.
=> Terraform network infrastructure

.github/workflows/tf_apply_production.yml, .github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_production.yml, .github/workflows/tf_plan_staging.yml, terragrunt/aws/api/iam.tf, terragrunt/aws/api/inputs.tf, terragrunt/aws/api/lambda.tf, terragrunt/aws/api/outputs.tf, terragrunt/aws/api/ssm.tf, terragrunt/aws/ecr/outputs.tf, terragrunt/env/production/api/terragrunt.hcl, terragrunt/env/staging/api/terragrunt.hcl
Adding Terraform code for the creation of lambda function, IAM groups, and SSM. Closes #70
=> API terraform infrastructure

.github/workflows/build_and_push_staging.yml
Github action to build a container and push it to ECR in staging. Closes #101
=> Github action to build container and push it to ECR in staging

terragrunt/env/production/api/.terraform.lock.hcl, terragrunt/env/production/ecr/.terraform.lock.hcl, terragrunt/env/production/hosted_zone/.terraform.lock.hcl, terragrunt/env/production/network/.terraform.lock.hcl, terragrunt/env/staging/api/.terraform.lock.hcl, terragrunt/env/staging/ecr/.terraform.lock.hcl, terragrunt/env/staging/hosted_zone/.terraform.lock.hcl, terragrunt/env/staging/network/.terraform.lock.hcl
Adding terraform.lock files to pin the provider and module versions. Closes #91
=> Adding terraform.lock files that will pin the provider and module versions

.github/workflows/tf_apply_production.yml, .github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_production.yml, .github/workflows/tf_plan_staging.yml, terragrunt/aws/api/lambda.tf, terragrunt/aws/api/outputs.tf, terragrunt/aws/cloudfront/certificate.tf, terragrunt/aws/cloudfront/cloudfront.tf, terragrunt/aws/cloudfront/inputs.tf, terragrunt/aws/cloudfront/route53.tf, terragrunt/aws/cloudfront/waf.tf, terragrunt/env/production/cloudfront/terragrunt.hcl, terragrunt/env/staging/cloudfront/.terraform.lock.hcl, terragrunt/env/staging/cloudfront/terragrunt.hcl
Terraform code to setup the Cloudfront, Certificate, Route53 and WAF. Closes #72
=> URL shortener cloud infrastructure 

.github/workflows/tf_apply_production.yml, .github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_production.yml, .github/workflows/tf_plan_staging.yml, terragrunt/aws/dynamodb/outputs.tf, terragrunt/aws/dynamodb/url_shortener_table.tf, terragrunt/env/production/api/terragrunt.hcl, terragrunt/env/production/dynamodb/terragrunt.hcl, terragrunt/env/staging/api/terragrunt.hcl, terragrunt/env/staging/dynamodb/.terraform.lock.hcl, terragrunt/env/staging/dynamodb/terragrunt.hcl
Terraform files for creating the dynamodb configuration. Closes #68
=> Adding files necessary to create the dynamodb configuration

.github/workflows/terraform_security_scan.yml, terragrunt/.checkov.yml
Adding checkov github action along with a .checkov.yml configuration file. Was not sure about some of the rules, so any input of rules to fix will be appreciated. Closes #90
=> Adding checkov github action and configuration file 

api/requirements.txt
Manually updates starlette and fast api to help close #108
=> fix: starlette and fast api

.github/workflows/docker-build.yml, api/Dockerfile, api/bin/entry.sh, api/main.py, api/requirements.txt
Modifying the Docker file, adding the Mangum handler to the main file and adding further packages to the requirements file. The URL shortener is still not working properly but at least now we can communicate with the lambda function.
=> Adding files rquired for lambda function to run and start in AWS

terragrunt/aws/cloudfront/waf.tf
Tweaking the regular expressions in WAF to allow required traffic.
=> Tweaking the regex expressions so that we allow traffic matching the regex

.github/workflows/build_and_push_staging.yml, api/templates/base.html, terragrunt/aws/api/ssm.tf, terragrunt/aws/cloudfront/waf.tf
Making necessary changes to finally get the url shortener working.
=> Adding files to make changes required for the url shortener to work

.github/workflows/tf_apply_production.yml, .github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_production.yml, .github/workflows/tf_plan_staging.yml, terragrunt/.checkov.yml, terragrunt/aws/alarms/alarms.tf, terragrunt/aws/alarms/input.tf, terragrunt/aws/alarms/local.tf, terragrunt/aws/alarms/queries.tf, terragrunt/aws/alarms/slack.tf, terragrunt/aws/alarms/sns.tf, terragrunt/env/production/alarms/terragrunt.hcl, terragrunt/env/staging/alarms/.terraform.lock.hcl, terragrunt/env/staging/alarms/terragrunt.hcl
Adding Error and Warning alarms for the Cloudwatch events due to the Lambda function. The Alarm messages will go to the following channels:
#url-shortner-staging-ops - Output from staging environment 
#url-shortener-prod-ops - Output from the production environment. 
Closes #111
=> Adding Slack alarms for the url shortener lambda function

terragrunt/aws/hosted_zone/route53.tf
Closes #141. This PR adds a route 53 health check to make sure the lambda keeps warm.
=> feat: add route53 health check

terragrunt/aws/cloudfront/iam.tf
@sylviamclaughlin This should fix the apply error observed in: https://github.com/cds-snc/url-shortener/actions/runs/4442664957/jobs/7799115730
Can you review?
=> Fixed kms key policy

terragrunt/aws/cloudfront/iam.tf
Messed up the principal, need to specify account id.
Failed apply: https://github.com/cds-snc/url-shortener/actions/runs/4450689114/jobs/7816450619
@sylviamclaughlin Can you review again pls?
=> Fixed iam principal arn

terragrunt/aws/api/iam.tf
Since the query has changed to the dynamodb table, need to add the Query permission to IAM.
=> Adding Query permission to IAM policy

api/utils/session.py, terragrunt/aws/cloudfront/waf.tf
This PR fixes the WAF rule to allow magic links and hopefully fixes the cookie?
=> fix: waf rule and cookie?

terragrunt/aws/cloudfront/cloudfront.tf, terragrunt/aws/dynamodb/url_shortener_table.tf
This PR fixes cookies in cloudfront by syncing the TF to the managed policies already click-opsed into the state. Also fixes the flip flopping of the dynamodb table.
=> find: delta

.github/workflows/tf_apply_production.yml, .github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_production.yml, .github/workflows/tf_plan_staging.yml, terragrunt/aws/api/iam.tf, terragrunt/aws/api/inputs.tf, terragrunt/aws/api/ssm.tf
Add two new SSM parameters with the App and Notify static Bearer tokens.
This will break the Staging API until #212 is merged.
- #192
- #212
=> feat: add SSM parameters with bearer auth tokens

api/Dockerfile, api/requirements.txt
Update how the `aws` cli is installed to prevent conflicts with the project's Python dependencies.
=> fix: update how aws is installed in Dockerfile

adr/2023-04-13-db-choice-and-design.md, adr/2023-04-13-ui.md
Closes #13 and closes #69 by adding ADRs for DynamoDB and the UI
=> Feat/dynamo and UI adr

.github/workflows/smoke_test.yml
Closes #257 by adding a nightly smoke test
=> feat: smoke test

.github/workflows/tf_apply_production.yml, .github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_production.yml, .github/workflows/tf_plan_staging.yml, terragrunt/aws/conformance_pack/cds_conformance_pack.tf, terragrunt/aws/conformance_pack/inputs.tf, terragrunt/env/staging/conformance_pack/.terraform.lock.hcl, terragrunt/env/staging/conformance_pack/terragrunt.hcl
Added the cds custom conformance pack module to the Url shortener terraform code.
=> Adding conformance pack module to the url shortener terraform code

terragrunt/aws/api/sentinel.tf, terragrunt/aws/network/vpc.tf
Update to the latest Sentinel layer version.
Remove the duplicated VPC flow logs.
=> fix: bump Sentinel layer version

api/utils/helpers.py
Remove the warning log as this will become noisy as the service is fuzzed without providing any value.
=> chore: remove SUSPICIOUS log on invalid token

.github/workflows/dast_scan.yml, .github/workflows/smoke_test.yml, .github/workflows/workflow_failure.yml
Update the DAST and smoke test workflows to run when there are new deployments to Staging or Prod.
=> feat: run DAST and smoke tests on all new deploys

.github/manifests/lambda_api_version
Update the API to include the JWT login token spam protection.
=> release: JWT login token

.github/workflows/tf_drift_check.yml, .github/workflows/workflow_failure.yml
Add a workflow that checks if there is drift between the infrastructure and the project's Terraform.
- Closes #328
=> feat: add Terraform drift check

.github/workflows/build_and_push_staging.yml
Part of #274. This PR adds in code to use the blue/green deploy step in staging CI.
=> feat: Add green/blue deploy step to staging CI

adr/2023-01-31-infrastructure-architecture.md, adr/2023-02-06-api-architecture.md, adr/2023-04-13-db-choice-and-design.md, adr/2023-04-13-ui.md
Update all ADR's to approved status.
=> docs: update ADR status to approved
