cds-snc/url-shortener

.gitignore
Added terragrunt and terraform lock and cache files to be ignored by github.
=> Adding terraform and terragrunt in the git ignore file

.github/workflows/export_github_data.yml
Update GitHub exporter workflow to include checkout step.
- cds-snc/platform-core-services#204
=> fix: add checkout to GitHub exporter workflow

terragrunt/.checkov.yml, terragrunt/Makefile, terragrunt/env/common/common_variables.tf, terragrunt/env/common/provider.tf, terragrunt/env/production/env_vars.hcl, terragrunt/env/staging/env_vars.hcl, terragrunt/env/terragrunt.hcl
Creating the initial directory structure for the URL shortener infrastructure and closes #47 . Current directory structure is as follows:
````
sylviamclaughlin@SMCLAUGHLIN url-shortener % tree terragrunt
terragrunt
├── Makefile
├── aws
│   ├── alarms
│   ├── api
│   └── hosted_zone
└── env
├── common
│   ├── common_variables.tf
│   └── provider.tf
├── production
│   ├── alarms
│   ├── api
│   ├── env_vars.hcl
│   └── hosted_zone
├── staging
│   ├── alarms
│   ├── api
│   ├── env_vars.hcl
│   └── hosted_zone
└── terragrunt.hcl
15 directories, 6 files
=> Initial terragrunt/terraform directory structure

.devcontainer/devcontainer.json
Add Terraform and Terragrunt to the devcontainer
using the `terraform` feature.
=> feat: add Terraform to devcontainer

.github/workflows/ci_code.yml, README.md, api/pytest.ini, api/routers/shortener.py, api/tests/routers/test_shortener.py, api/utils/helpers.py
Closes #83. This PR renames the `shorten` route to `v1`. We decided not to overload the `POST /` route with JSON and Form Data because of future UI considerations. Renaming it to `v1` allows for future versions of APIs to be implemented.
=> feat: Rename route to v1

.github/workflows/build_and_push_staging.yml
Correcting the name of the URL shortener ECR registry since it was previously incorrect and the action was failing.
=> Fixing a bug in the ECR registry name

terragrunt/aws/cloudfront/cloudfront.tf
I had previously omitted the required values for the cloudfront distribution and terraform apply was failing even though terraform plan was fine.
=> Added the forwarded values for the cloudfront distribution

api/bin/entry.sh
=> Fixing up slashes from api-auth-token to api_auth_token

terragrunt/aws/api/lambda.tf, terragrunt/aws/api/ssm.tf
Closes https://github.com/cds-snc/url-shortener/issues/143.
This PR moves ALLOWED_DOMAINS from aws_ssm_parameter resource to lambda environment variables.
=> fix: moved ALLOWED_DOMAINS from ssm to lambda env

.github/workflows/build_and_push_staging.yml, terragrunt/aws/api/iam.tf
Closes #132 . The following changes were made:
- Added the DescribeTable permission to the IAM roles for DynamoDB since the healthcheck was needing this permission (thus the reason for failing)
- Changed the build and push to staging workflow to build and push to staging when there is a terraform change as well.
=> Healthcheck fix

terragrunt/aws/api/iam.tf
This closes https://github.com/cds-snc/url-shortener/issues/172
Root cause: The IAM permission to read hashing_peppers ssm resource is missing.
Added missing IAM permission.
=> Added IAM permission to read hashing_peppers from parameter store

terragrunt/aws/cloudfront/waf.tf
Due to the [deterministic hashing change](https://github.com/cds-snc/url-shortener/pull/153), the character set for shortened url has changed to only [0-9A-Za-z]. I am modifying the Waf regex rules to allow only those character sets.
=> Modifying WAF regex rules to allow [0-9A-Za-z] character set

api/tests/utils/test_helpers.py, api/utils/helpers.py
This closes: https://github.com/cds-snc/url-shortener/issues/148
Added validation to only allow `https` as a scheme.
=> Only allow https as URL scheme

terragrunt/aws/cloudfront/waf.tf
This closes: https://github.com/cds-snc/url-shortener/issues/176
The [doc](https://registry.terraform.io/providers/hashicorp/aws/4.52.0/docs/resources/wafv2_web_acl_logging_configuration) mentioned firehose is required. But this may not be the case fore CloudWatch Logs log group.
=> Enabled WAF logging to cloudwatch logs log group

terragrunt/aws/cloudfront/iam.tf, terragrunt/aws/cloudfront/waf.tf
This closes: https://github.com/cds-snc/url-shortener/issues/178
Added Key policy to KMS so that it can be accessed by Cloudwatch logs log group.
=> KMS key policy to allow Cloudwatch logs access

terragrunt/.checkov.yml, terragrunt/aws/cloudfront/iam.tf
@sylviamclaughlin I think I found out what the issue is. FYI, I haven't run apply manually yet.
The issue appears to be for CMK, resources must be set to "*", which checkov dislikes.
The AWS documentation does not talk about this. However, per [stackoverflow](https://stackoverflow.com/questions/41991480/the-new-key-policy-will-not-allow-you-to-update-the-key-policy-in-the-future):
The Resource: "*" [is required and is the only possible value](http://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html):
Resource – (Required) In a key policy, you use "*" for the resource, which means "this CMK." A key policy applies only to the CMK it is attached to.
See https://aws.amazon.com/premiumsupport/knowledge-center/update-key-policy-future/ for an example.
=> Fixed policy, suppress CKV_AWS_111

terragrunt/aws/cloudfront/iam.tf, terragrunt/aws/cloudfront/waf.tf
@sylviamclaughlin This fixes the tf apply issues. The logging resources must be in `us-east-1`. I still need to refine the metric filters a bit. It's too noisy because of the health check probes. I will do this in a separate PR.
Can you review?
=> Fix/kms policy typo, resources region

api/models/ShortUrls.py, api/tests/models/test_ShortUrls.py, api/tests/utils/test_helpers.py, terragrunt/aws/dynamodb/url_shortener_table.tf
Enabled TTL on the DynamoDB database to automatically delete and expire entries after 2 years. Closes #97 
Changes made:
- Terraform DynamoDB change to enable the TTL functionality
- Changed the create_short_url function to set the TTL for each entry to be epoch time of 2 years in the future
- Changed the get_short_url function to retrieve only entries that have a valid TTL. Since AWS does not automatically delete expired entries and it takes up to 48 hours for this change to be made, this was needed
- Wrote unit tests to test the above.
=> DynamoDB TTL integration (2 years)

terragrunt/aws/dynamodb/url_shortener_table.tf
I had the ttl value previously disabled, which I am fixing now.
=> Enabling TTL for the dynamoDB table

terragrunt/aws/api/iam.tf
This PR allows the IAM user to access the correct index on the dynamodb table
=> fix: index permissions

api/static/css/styles.css
Closes #225. Adds CSS word-break to wrap URLs.
=> fix: word break

api/Dockerfile, api/requirements.txt
Update the Dockerfile and requirements.txt file to move the dependencies needed for Lambda only into the Dockerfile.
=> fix: move lambda specific deps to Dockerfile

.devcontainer/devcontainer.json, .github/workflows/cypress_e2e.yml, .github/workflows/loadtesting.yml, README.md, api/Makefile, api/loadtesting/test.js
Closes #195.
Adds k6 load testing tool. This will simulate different loads of users for one minute who lookup a short URL and also create a short URL using the API. Expected thresholds are
- less than 1% request fail
- 95 percent of response times must be below some reasonable amount of milliseconds based on the hardware that is running the server.
Currently we have three profiles
- `ci` - expected to pass on GitHub Action Runners
- `dev` - expected to pass in a devcontainer
- `staging` - expected to pass against staging.
The profiles look as follows right now:
```
const profiles = {
ci: {
host: 'http://0.0.0.0:8000/',
createShortUrlVus: 10,
duration_p95_createShortUrl: '2000',
redirectPageVus: 100,
duration_p95_redirectPage: '500',
},
dev: {
host: 'http://127.0.0.1:8000/', …
```
=> feat: loadtesting

api/utils/helpers.py, terragrunt/aws/alarms/alarms.tf
Changing some of the error messages from error to warning so that they are less noisy. Moved them from log.error to log.warning, which should make the messages more meaning. The treshold for warning is 5 as opposed to 1. 
Since we want to capture all json logs that contain the word "Error", I changed the message in the logs to not contain error so that the alarm is not triggered.
=> Tweak error messages to make them less noisy when alarming

adr/2023-01-31-infrastructure-architecture.md
Added to the Infrastructure ADR the backup plan that we wrote in order to meet ATO compliance. 
Let me know if the explanation is insufficient.
=> Adding Backup plan to the Infrastructure ADR

terragrunt/aws/network/vpc.tf
Closes #251. Updating the VPC version of the url shortener to v.5.1.5 since it contains the latest vpc changes in order to meet ATO compliance.
=> Update vpc version to 5.1.5

.github/workflows/tf_apply_production.yml, .github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_production.yml, .github/workflows/tf_plan_staging.yml, terragrunt/aws/api/iam.tf, terragrunt/aws/api/inputs.tf, terragrunt/aws/api/lambda.tf, terragrunt/aws/api/ssm.tf
Update the `api` module to add the `NOTIFY_CONTACT_EMAIL` secret that will be the email address that contact form submissions are sent to.
Also updates the lambda function with the contact form's Notify template ID.
- #158
=> feat: add contact form target email address

terragrunt/aws/cloudfront/waf.tf
Allow the English and French Contact us paths through the firewall.
Also update the other regular expressions to allow an optional trailing `/` and tighten down the static files path.
- Closes #158
=> fix: add contact paths to the firewall

.github/workflows/tf_apply_production.yml, .github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_production.yml, .github/workflows/tf_plan_staging.yml, terragrunt/aws/api/inputs.tf, terragrunt/aws/api/sentinel.tf
Add the CloudWatch log group forwarder to send the API's logs to Sentinel.
- #265
=> feat: forward API logs to Sentinel

terragrunt/aws/api/sentinel.tf
Add a CloudWatch subscription filter to trigger the forwarding of matching log messages to Sentinel.
- #265
=> fix: add Sentinel forward log group filter

terragrunt/aws/api/sentinel.tf
Update the CloudWatch log subscription for Sentinel to use the log group name.
- #265
=> fix: use log group name for CloudWatch filter

.github/workflows/tf_apply_production.yml, .github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_production.yml, .github/workflows/tf_plan_staging.yml
Update the Terraform workflows to use the correct
Sentinel workspace key and ID.
- #265
=> fix: use the correct Sentinel action secrets

.github/workflows/codeql_scan.yml, .github/workflows/dast_scan.yml
Add GitHub workflows to perform CodeQL static code analysis and dynamic vulnerability scans with DASTardly.
- #279 
- cds-snc/url-shortener-documentation#451
=> feat: add CodeQL and DAST scanning

terragrunt/aws/cloudfront/iam.tf, terragrunt/aws/cloudfront/locals.tf, terragrunt/aws/cloudfront/waf.tf
Update the firewall logging configuration to send all access logs to the Cloud Based Sensor satellite bucket. This allows CCCS to monitor and perform forensic analysis.
Removes the WAF ACL CloudWatch log group and its associated KMS key as a WAF ACL can only have one access log destination.   Unfortunately this also means we need to remove the metric log filters that were created on this log group.
Finally, removes the IP allow list for health checking as right now all global traffic is allowed so we don't need to specifically allow IPs based on their geolocation.
- cds-snc/url-shortener-documentation#71
=> fix: send WAF ACL access logs to CBS

api/tests/utils/test_helpers.py, api/utils/helpers.py
This addresses https://github.com/cds-snc/url-shortener/issues/284
Per [discussion](https://gcdigital.slack.com/archives/C04J7RT0FQD/p1682011669452889), it is desirable to improve readability and reduce the likelihood of accidental obscenity in a shortened URL. It is also desirable to follow the guidance set forth by covid alert because it has been tested and approved in both French and English. This implementation: - follows covid alert guidance to use the character set in `AEFHJKLQRSUWXYZ` and `2456789`
- includes the use of lower case characters to reduce the probability of a collision
- excludes `uU` to reduce the likelihood of accidental obscenity per Crockford's Base 32 encoding
@patheard , @sylviamclaughlin Can you review?
=> Added translation of hash to safe char set

api/middleware/cloudfront.py, api/utils/auth_token.py, api/utils/magic_link.py, api/utils/session.py, terragrunt/aws/alarms/alarms.tf, terragrunt/aws/alarms/input.tf, terragrunt/aws/alarms/local.tf, terragrunt/aws/alarms/queries.tf, terragrunt/env/production/alarms/terragrunt.hcl, terragrunt/env/staging/alarms/terragrunt.hcl
- Add logging for events that are suspicious if more than a certain threshold occur.
- Add a CloudWatch alarm that triggers if more than 5 suspicious events are logged in a 5 minute period.
- Add a CloudWatch log insight query to view suspicious events.
- cds-snc/url-shortener-documentation#69
=> feat: audit suspicious events and add alarm

api/utils/auth_token.py, api/utils/session.py
Update the suspicious log wording to avoid accidentally triggering the error alarm which has a metric on the word `failed`.
- #293
=> fix: change suspicious log wording

terragrunt/aws/conformance_pack/cds_conformance_pack.tf
PR to exclude rules that are not applicable to the URL shortener. More rules will be added later. The current rules excluded are:
1. LambdaDlqCheck - Config rule name [lambda-dlq-check](https://ca-central-1.console.aws.amazon.com/config/home?region=ca-central-1#/rules/details?configRuleName=lambda-dlq-check-conformance-pack-75rwmzoyh). This is not applicable to us since we are not invoking Lambdas asynchronously.
2. LambdaFunctionPublicAccessProhibited - Config rule name [lambda-function-public-access-prohibited](https://ca-central-1.console.aws.amazon.com/config/home?region=ca-central-1#/rules/details?configRuleName=lambda-function-public-access-prohibited-conformance-pack-75rwmzoyh). We need our lambda function to be publicly available for the url shortener to work. 
3. …
=> Exclude rules from conformance pack that are not applicable

.gitignore, terragrunt/aws/alarms/input.tf, terragrunt/aws/alarms/shield_advanced.tf, terragrunt/aws/cloudfront/outputs.tf, terragrunt/env/production/alarms/terragrunt.hcl, terragrunt/env/staging/alarms/terragrunt.hcl
Enrol the API's CloudFront distribution and Route53 hosted zone in AWS Shield Advanced.
- #276
=> feat: enrol in AWS Shield advanced

terragrunt/aws/alarms/slack.tf
Update the Slack notify lambda function to allow the US East 1 SNS Topic to invoke it.  This topic is used by the AWS Shield Advanced DDoS alarms.
- Closes #276
=> fix: slack notify SNS topic ARNs

terragrunt/aws/conformance_pack/cds_conformance_pack.tf
Update the list of excluded rules and added a comment explanation for each.
Also no longer require a CloudWatch alarm `insufficient action` to be considered compliant.
- cds-snc/url-shortener-documentation#454
=> fix: exclude more config rules

terragrunt/aws/cloudfront/waf.tf
Update the WAF login URI path regex pattern set to have a unique name.
- #303 
- #298
=> fix: unique name for WAF's login URI path regex

.github/workflows/build_and_push_production.yml, .github/workflows/build_and_push_staging.yml, .github/workflows/deploy_api_production.yml
Add workflows to build/push the production Docker image and deploy new versions of the API.  The API prod deployment will be triggered by changes to a `.github/manifests/lambda_api_version` file, which will contain the Docker image tag to update the Lambda API function with.
Also narrows the workflow permissions on the Staging Docker build/push workflow.
- #298
=> feat: add production Docker workflows

.github/workflows/build_and_push_production.yml, api/routers/shortener.py, api/tests/routers/test_shortener.py
Add basic email validation before attempting to send the
magic link through Notify.
Also fix a bug with the prod Docker build/push workflow.
- #298
=> feat: validate email on login

terragrunt/env/production/alarms/terragrunt.hcl, terragrunt/env/production/backup_plan/.terraform.lock.hcl, terragrunt/env/production/backup_plan/terragrunt.hcl, terragrunt/env/production/conformance_pack/.terraform.lock.hcl, terragrunt/env/production/conformance_pack/terragrunt.hcl
Add the missing `backup_plan` and `conformance_pack` modules to the production Terragrunt configuration.
Also fixes the `alarms` module Terraform source reference.
- #298
=> fix: add missing prod Terragrunt modules

api/routers/shortener.py, api/templates/login.html, api/tests/routers/test_shortener.py
Add a honeypot field to the login form to cut down on bot spam from fuzzing attacks.
It is visually hidden and hidden from assistive technology.
=> feat: add honeypot to prevent login form spam

terragrunt/aws/backup_plan/locals.tf
The delete must be 90 days after the cold storage date.
=> fix: DynamoDB backup plan

.github/workflows/workflow_failure.yml
Only notify product Slack channel when listed GitHub workflows fail.
=> chore: limit workflow failure notifications

api/i18n/en.json, api/i18n/fr.json, api/logger.py, api/routers/shortener.py, api/tests/utils/test_helpers.py, api/utils/helpers.py, api/utils/magic_link.py, terragrunt/aws/alarms/cloudwatch_api.tf, terragrunt/aws/hosted_zone/route53.tf
- Update the app to include more log info statements.
- Update the ERROR CloudWatch metric to no longer count lowercase `error` and `warning` strings.
- Update the Route53 health check to use `/healthcheck`
- #330
=> feat: add info log statements

api/tests/utils/test_helpers.py, api/utils/helpers.py
Update the short URL resolve function to check that a found short URL still meets the `ALLOWED_DOMAINS` restrictions.
Remove 2 unit tests that were not working as expected and being tested as part of the ShortUrls model unit tests.
- #333
=> feat: check short URL still valid

terragrunt/aws/alarms/athena.tf
Add the Athena Terraform module which will allow us to easily inspect the WAF ACL access logs.
- #329
=> feat: add Athena queries for WAF access logs

terragrunt/aws/alarms/cloudwatch_api.tf, terragrunt/aws/cloudfront/waf.tf
Add a WAF ACL `challenge` rule for the login paths.  This will cause the [WAF to issue a transparent challenge](https://docs.aws.amazon.com/waf/latest/developerguide/waf-captcha-and-challenge.html) to all requests to the login URLs to stop bot access.
Update the ERROR metric to remove the word `failed` to avoid triggering on the added user info logging.
- #327
=> feat: WAF ACL login challenge

terragrunt/aws/cloudfront/cloudfront.tf
Update the CloudFront CSP so that the WAF ACLs challenge rule can sent and verify challenge tokens.
- #336 
- #327
=> fix: CloudFront CSP to support WAF challenge

.github/workflows/build_and_push_staging.yml, terragrunt/aws/api/lambda.tf
Part of #274. This PR adds the alias `latest` to the terraform code while ignoring any changes to the function version and routing configuration which will be handled by the green/blue deploy action. It also re-routes the function url to the `latest` alias.
=> fix: green/blue versions

api/routers/shortener.py, api/tests/utils/test_magic_link.py, api/utils/magic_link.py
Closes #346. Fixes an issues where `gc.ca` is a valid email domain but `tbs-sct.gc.ca` is not. The edge case to check for is somebody trying to register with `foogc.ca`.
=> fix: email suffix checks

terragrunt/aws/alarms/cloudwatch_api.tf, terragrunt/aws/alarms/input.tf, terragrunt/aws/alarms/local.tf, terragrunt/env/production/alarms/terragrunt.hcl, terragrunt/env/staging/alarms/terragrunt.hcl
Add a CloudWatch alarm that triggers when a high number of magic link emails have been sent in a 5 minute period.
This is being done to watch for abuse of the Notify API key.
=> feat: alarm for high number of magic link emails

api/routers/ops.py, api/utils/contact.py, api/utils/helpers.py, api/utils/magic_link.py
Update the `log.error` to print stack traces when an Exception is caught.
- #355
=> fix: print stack trace when Exceptions are caught

api/models/ShortUrls.py, api/tests/models/test_ShortUrls.py, api/utils/helpers.py
Implemented a last access date that gets updated every time the shortened url is retrieved. Also, set the expiry date or ttl of the dynamobd entry to be 2 years since the last access date. 
Closes #275
=> Expiry of Urls after 2 years since last access date

api/templates/base.html
Update to the new `gcds-utility.css` file.
=> fix: update to new GCDS utility CSS path

.devcontainer/docker-compose.yml, .github/workflows/cypress_e2e.yml, .github/workflows/loadtesting.yml, api/main.py, api/pytest.ini, api/routers/shortener.py, api/tests/utils/test_helpers.py, api/utils/helpers.py, terragrunt/aws/api/lambda.tf
Update the allowed email domains and allowed shortened domains to be controlled by two distinct environment variables.
This will allow us to have more fine grained control over which email domains can login and which URLs can be shortened.
- #367 
- cds-snc/security-risk-register#151
=> fix: split the ALLOWED_DOMAINS into two env vars

.github/workflows/deploy_api_production.yml, adr/2023-02-06-api-architecture.md, api/routers/ops.py, api/tests/routers/test_ops.py, terragrunt/aws/cloudfront/cloudfront.tf, terragrunt/aws/cloudfront/waf.tf, terragrunt/aws/hosted_zone/route53.tf
Remove the `/healthcheck` endpoint that queries DynamoDB and replace it with the `/version` endpoint.
This is being done to address the security risk identified of unauthenticated requests to our data source being used in a DoS attack.
- cds-snc/security-risk-register#150
=> fix: use `/version` endpoint for healthcheck

api/utils/session.py
Update the cookie so that it can no longer sent in plaintext with unecrypted requests.
- cds-snc/security-risk-register#147
=> fix: set cookie `secure=True` attribute

api/i18n/en.json, api/i18n/fr.json, api/tests/utils/test_helpers.py, api/utils/helpers.py
Update the URL validation logic to prevent URLs longer than 2048 characters from being shortened.
For simplicity, I am continuing to return a `400` HTTP status code from the API if this error condition is triggered.
- cds-snc/security-risk-register#153
=> fix: set max URL length that can shorten

api/utils/magic_link.py
Update the magic link login process so that successful logins do not remove the GUID.  This is being done so that systems with automatic link validation do not claim the user's session before they can.
- #379
=> fix: do not delete magic link

api/models/MagicLinks.py, api/tests/models/test_MagicLinks.py
Update the magic link `get` method to return the record's `ttl` so that it can be compared to the current time.
Prior to this fix, `"ttl" in response["Item"]` was False, which meant that the magic link remained valid up until DynamoDB cleaned up expired items.
- #380
=> fix: return the record `ttl` field

api/utils/helpers.py
Update the logging for an unresolvable URL to `info` so that we're not alerted during fuzzing attacks.
=> chore: log info when URL cannot be resolved

terragrunt/aws/cloudfront/route53.tf
Remove the Route53 DNS resolver firewall as this will become a challenge to maintain with how each CNAME in the DNS chain must be allowed for a URL to resolve properly when adding a short URL.
- cds-snc/platform-core-services#361
=> fix: remove the Route53 DNS resolver firewall

api/bin/entry.sh
Update how the API's SSM ParameterStore params are retrieved to use a single API call.  Also adds a check to cause the entry.sh to fail if secrets are not retrieved.  Since this will block the start of the lambda function code, it should cause the broken function to be discarded and replaced.
This change is being made to try to avoid scenarios we have seen where a lambda function gets initialized missing some of its secrets.
- #388
=> fix: retrieve API secrets in one API call

api/bin/entry.sh
Fix the missing `fi` from the Docker entry.sh.
- #397 
- #388
=> fix: add closing `fi` to entry.sh

api/bin/entry.sh
Update the API's `entry.sh` to always check if the temporary `.env` file contains secrets before starting the function.
- #388
=> fix: always check if secrets exist for entry.sh

api/bin/entry.sh
Update the API's `entry.sh` to delete the temp `.env` file if it was not loaded properly.  This will allow subsequent lambda invocations to attempt to reload the secrets instead of being caught in a broken state.
- #388
=> fix: remove temp `.env` file if not populated

api/bin/entry.sh
Update the API's Docker entry.sh with log level labels.  This will allow warnings to be caught by the CloudWatch metric filters and trigger alarms.
- #388
=> fix: add log level labels to Docker entry.sh

.devcontainer/docker-compose.yml, .github/workflows/ci_code.yml, .github/workflows/cypress_e2e.yml, .github/workflows/loadtesting.yml
Update the DynamoDB local AWS access key to conform to the new [v2.0 requirements](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html):
> DynamoDB local version 2.0.0 and greater AWS_ACCESS_KEY_ID
> can contain the only letters (A–Z, a–z) and numbers (0–9).
=> fix: DynamoDB local AWS access key
